min_particles: 30
max_particles: 500
update_min_a: 0.261
update_min_d: 0.1
laser_min_range: -1
laser_max_range: -1
laser_max_beams: 30
laser_z_hit: 0.95
laser_z_rand: 0.05
odom_alpha1: 0.1
odom_alpha2: 0.1
odom_alpha3: 0.1
odom_alpha4: 0.1
